language: node_js
node_js:
  - "6"
install:
  - yarn install
script:
  - yarn run
  - bash ./travis/gh-pages.sh
env:
  global:
  - ENCRYPTION_LABEL: "6914688fca78"
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
  - SOURCE_BRANCH: "master"
  - DEPLOY_DIR: "public"
